# Primer contacto con datos

* Construir una forma de trabajo:
    * aprender a observar un conjunto de datos
    * comprender que representa
    * detectar problemas
    * seleccionar información relevante
    * realizar cálculos
    * resumir resultados
    * crear visualizaciones
    * comunicar conclusiones de manera clara

## ¿Por qué aprender a trabajar con datos?

* Vivimos rodeados de datos
* Tener datos no significa automáticamente comprender una situación
* Para que esos datos sean útiles, necesitamos hacerles preguntas, revisarlos, ordenarlos, limpiarlos, analizarlos e interpretarlos
* Trabajar con datos implica combinar herramientas técnicas con interpretación

## Dato, información y conocimiento

$$\text{datos} \rightarrow \text{información} \rightarrow \text{conocimiento}$$

* **Dato**: es un valor registrado. Ejemplo: 8
* **Información**: dato aparece dentro de un contexto. Ejemplo: la nota de Pepe en matemáticas fue 8
* **Conocimiento**: aparece cuando podemos interpretar esa información, relacionarla con otros datos y utilizarla para tomar decisiones o comprender mejor una situación. Ejemplo: Pepe obtuvo un 8 en Matemática. Su promedio anterior era 6,5 y en las últimas semanas aumentó la cantidad de horas de estudio. Su desempeño parece haber mejorado

## ¿Qué significa analizar datos?

* Observar un conjunto de datos con el objetivo de comprender mejor una situación, responder preguntas o tomar decisiones fundamentadas
* No se trata solamente de aplicar fórmulas o ejecutar código
* El análisis de datos suele ser un proceso que incluye varias etapas:
    1. comprender el contexto
    2. observar los datos
    3. comenzar a hacer preguntas: ¿Cuál es el promedio? ¿Qué diferencias aparecen entre distintas categorías?
    4. interpretar los resultados
    5. comunicar lo encontrado mediante tablas, gráficos, dashboards, informes o explicaciones escritas

## ¿Qué es un dataset?

* Es un conjunto organizado de datos
* En muchos casos, se presenta como una tabla formada por filas y columnas
* Cada fila suele representar una observación, un registro o un caso
* Cada columna representa una característica, atributo o variable que se registró para cada observación
* Ejemplo:

|nombre	| edad	| curso	| horas_estudio	| nota |
| --    | --    | --    | --            | --   |
| Ana	| 15	| 3A	| 4	            | 8    |
| Bruno	| 16	| 3B	| 2	            | 6    |
| Carla	| 15	| 3A	| 6	            | 9    |
| Diego	| 17	| 4A	| 1	            | 5    |
| Elena	| 16	| 3B	| 5	            | 8    |

* Esta forma de organizar los datos es muy frecuente porque permite comparar casos, resumir información, buscar patrones y hacer preguntas como: ¿Los estudiantes que estudiaron más horas obtuvieron mejores notas?

## Filas, columnas, variables, observaciones y valores

* Cuando observamos un dataset tabular, es importante reconocer sus partes principales:

| Elemento	| Qué representa                      | Ejemplo                 |
| --------- |-------------------------------------|-------------------------|
| Fila	    | Una observación, registro o caso    | Un estudiante           |
| Columna	| Una variable o característica       | La nota                 |
| Valor	    | Un dato concreto dentro de la tabla | 8                       |
| Dataset	| El conjunto completo de datos       | La tabla de estudiantes |

## Tipos de variables

No todas las columnas de un dataset representan el mismo tipo de información. Algunas contienen números, otras contienen categorías, otras fechas y otras textos.

| Tipo de variable | Que representa                                                 | Ejemplos                          |
|------------------|----------------------------------------------------------------|-----------------------------------|
| numérica         | cantidad o medidas                                             | edad, notas, precio               |
| num. discreta    | valores contables                                              | cant. de estudiantes              |
| num. continua    | valores dentro de un rango                                     | altura, peso, temperatura         |
| categóricas      | grupos, clases o etiquetas                                     | curso, pcia, tipo prod, color     |
| ordinales        | categorías que tienen un orden natural                         | bajo/medio/alto                   |
| temporales       | fechas, horas o momentos en el tiempo                          | fecha de compra, fecha nacimiento |
| texto            | frases, comentarios, descripciones u otros fragmentos escritos | comentario, desc prod, observac   |

En general, antes de analizar una columna conviene preguntarnos: ¿qué tipo de información contiene? Esa respuesta nos ayuda a decidir qué operaciones tienen sentido y cuáles no.

## Primer dataset en Python

* Biblioteca Pandas
* Pandas permite trabajar con datos organizados en forma de tabla (DataFrame)
* Un DataFrame es una tabla de datos: tiene filas, columnas y valores
* Ejemplo: dataset de estudiantes
* diccionario de Python → DataFrame de Pandas

In [1]:
# Importamos la biblioteca Pandas
# Por convención, se suele importar con el alias pd

import pandas as pd

# Creamos un diccionario de Python
# Cada clave del diccionario será el nombre de una columna
# Cada lista contiene los valores de esa columna

datos = {
    "nombre": ["Ana", "Bruno", "Carla", "Diego", "Elena"],
    "edad": [15, 16, 15, 17, 16],
    "curso": ["3A", "3B", "3A", "4A", "3B"],
    "horas_estudio": [4, 2, 6, 1, 5],
    "nota": [8, 6, 9, 5, 8]
}

# Convertimos el diccionario en un DataFrame de Pandas
# A partir de este momento, los datos quedan organizados como una tabla

df = pd.DataFrame(datos)

# Mostramos el DataFrame

df

  nombre  edad curso  horas_estudio  nota
0    Ana    15    3A              4     8
1  Bruno    16    3B              2     6
2  Carla    15    3A              6     9
3  Diego    17    4A              1     5
4  Elena    16    3B              5     8

* Se observa:
    * las columnas describen variables
    * las filas representan observaciones
    * el índice identifica las filas dentro del DataFrame

## Hacer preguntas sobre un dataset

* Simples y directas: ¿cuántos estudiantes hay en el dataset?
* Relacionan 2 o más variables: ¿los estudiantes que estudiaron más horas obtuvieron mejores notas?
* Complejas: ¿estudiar más horas causa mejores resultados?

## Primeras respuestas usando pandas

In [2]:
cantidad_estudiantes = len(df)
nota_mas_alta = df["nota"].max()
nota_mas_baja = df["nota"].min()
promedio_notas = df["nota"].mean()
estudiantes_por_curso = df["curso"].value_counts()

* Una salida como: 7.2 no dice demasiado por sí sola. Pero si sabemos que representa el promedio de notas de un grupo de estudiantes, entonces se convierte en información útil
* En análisis de datos, muchas veces vamos a realizar este recorrido:

$$\text{código} \rightarrow \text{resultado} \rightarrow \text{interpretación}$$

* El código produce un resultado. Luego debemos leer ese resultado dentro del contexto del problema
* Por eso, cada vez que obtengamos una tabla, un número o un gráfico, conviene hacernos algunas preguntas:
    * ¿Qué representa este resultado?
    * ¿A qué columna o variable se refiere?
    * ¿En qué contexto debe interpretarse?
    * ¿Qué conclusión puedo sacar?
    * ¿Qué conclusión no debería sacar todavía?
* Esta costumbre ayuda a evitar interpretaciones apresuradas o conclusiones que los datos no sostienen

## Relacionar variables

* Hasta ahora hicimos preguntas sobre columnas individuales
* Pregunta relacionando las variables: horas_estudio y nota: ¿Los estudiantes que estudiaron más horas obtuvieron mejores notas?

In [3]:
df2 = df[["horas_estudio", "nota"]]
df2

   horas_estudio  nota
0              4     8
1              2     6
2              6     9
3              1     5
4              5     8

Se observa: que en este pequeño dataset, los estudiantes con más horas de estudio parecen tener notas más altas

## Los límites de un dataset

* Un dataset puede ayudarnos a comprender una situación, pero no contiene toda la realidad.
* Hay muchas otras preguntas que no podemos responder con este dataset
    * ¿Qué tema se evaluó?
    * ¿La evaluación fue fácil o difícil?
* Un dataset siempre es una representación parcial de una situación
* Antes de sacar conclusiones, conviene preguntarnos:
    * ¿Qué información tenemos?
    * ¿Qué información falta?
    * ¿Cómo fueron obtenidos estos datos?
    * ¿Qué tan confiables son?
    * ¿Qué conclusiones permite sostener este dataset?
    * ¿Qué conclusiones serían exageradas?
* Esta mirada crítica es parte esencial del trabajo con datos

## Los datasets reales suelen tener problemas

* En situaciones reales, los datasets suelen ser más desordenados en comparación al dataset de estudiantes
* Podemos encontrar problemas como estos:

| Problema                     | Ejemplo                                                       |
|------------------------------|---------------------------------------------------------------|
| Datos faltantes              | Una fila no tiene cargada la edad o la nota                   |
| Valores duplicados           | El mismo estudiante aparece dos veces por error               |
| Nombres de columnas confusos | Una columna se llama col1 o dato_final                        |
| Espacios innecesarios        | El valor " 3A " aparece con espacios antes o después          |
| Diferencias de escritura     | Un curso aparece como 3A, 3a, 3 A o Tercero A                 |
| Tipos de datos incorrectos   | Una nota aparece como texto en lugar de número                |
| Valores imposibles           | Una edad de -5 o una nota de 25 si la escala va de 1 a 10     |
| Fechas mal cargadas          | Una misma fecha aparece como 2024-05-10, 10/05/2024 o mayo 10 |

* Estos problemas no son detalles menores. Si no los detectamos, pueden afectar los resultados del análisis
* Por eso, una parte muy importante del trabajo con datos consiste en revisar la calidad del dataset antes de analizarlo
* Antes de confiar en un resultado, debemos revisar los datos que usamos para obtenerlo.

## Algunas preguntas, algunas instrucciones

In [4]:
# filas y columnas
df.shape

(5, 5)

In [5]:
# nombre de columnas
df.columns

Index(['nombre', 'edad', 'curso', 'horas_estudio', 'nota'], dtype='str')

In [6]:
# notas registradas
df['nota']

0    8
1    6
2    9
3    5
4    8
Name: nota, dtype: int64

In [7]:
# cursos registrados
df['curso']

0    3A
1    3B
2    3A
3    4A
4    3B
Name: curso, dtype: str

# Primeras inspecciones de un Dataframe

* Antes de limpiar, transformar, resumir o visualizar datos, necesitamos saber con qué estamos trabajando (conocer su estructura)
* La inspección inicial es una etapa fundamental en cualquier análisis de datos
* Inspeccionar un DataFrame significa hacer una primera revisión para responder preguntas como estas:
    * ¿Cuántas filas tiene?
    * ¿Cuántas columnas tiene?
    * ¿Qué representa cada columna?
    * ¿Cómo se llaman las columnas?
    * ¿Qué tipos de datos contiene?
    * ¿Hay columnas numéricas?
    * ¿Hay columnas categóricas?
    * ¿Aparecen valores faltantes?
    * ¿Los datos parecen estar cargados correctamente?
* Esta revisión inicial nos ayuda a evitar errores

## Dataset de trabajo

In [8]:
import pandas as pd

datos = {
    "producto": [
        "Cuaderno", "Lapicera", "Mochila", "Regla", "Cartuchera",
        "Cuaderno", "Marcadores", "Carpeta", "Goma", "Lapiz"
    ],
    "categoria": [
        "Libreria", "Libreria", "Accesorios", "Libreria", "Accesorios",
        "Libreria", "Libreria", "Libreria", "Libreria", "Libreria"
    ],
    "precio": [
        1200, 350, 8500, 500, 3200,
        1250, 1800, 950, 300, 250
    ],
    "cantidad_vendida": [
        15, 40, 5, 25, 8,
        12, 10, 18, 30, 50
    ],
    "sucursal": [
        "Centro", "Centro", "Norte", "Sur", "Norte",
        "Sur", "Centro", "Norte", "Sur", "Centro"
    ],
    "fecha": [
        "2024-03-01", "2024-03-01", "2024-03-02", "2024-03-02", "2024-03-03",
        "2024-03-03", "2024-03-04", "2024-03-04", "2024-03-05", "2024-03-05"
    ]
}

df = pd.DataFrame(datos)
df

     producto   categoria  precio  cantidad_vendida sucursal       fecha
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
1    Lapicera    Libreria     350                40   Centro  2024-03-01
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
3       Regla    Libreria     500                25      Sur  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
5    Cuaderno    Libreria    1250                12      Sur  2024-03-03
6  Marcadores    Libreria    1800                10   Centro  2024-03-04
7     Carpeta    Libreria     950                18    Norte  2024-03-04
8        Goma    Libreria     300                30      Sur  2024-03-05
9       Lapiz    Libreria     250                50   Centro  2024-03-05

## Ver las primeras filas con head()

In [9]:
# primeras filas. Default: 5 filas
df.head()

     producto   categoria  precio  cantidad_vendida sucursal       fecha
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
1    Lapicera    Libreria     350                40   Centro  2024-03-01
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
3       Regla    Libreria     500                25      Sur  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03

In [10]:
# también se puede indicar cuántas filas queremos ver
df.head(3)

   producto   categoria  precio  cantidad_vendida sucursal       fecha
0  Cuaderno    Libreria    1200                15   Centro  2024-03-01
1  Lapicera    Libreria     350                40   Centro  2024-03-01
2   Mochila  Accesorios    8500                 5    Norte  2024-03-02

## Ver las últimas filas con tail()

In [11]:
# últimas filas. Default: 5 filas
df.tail()

     producto categoria  precio  cantidad_vendida sucursal       fecha
5    Cuaderno  Libreria    1250                12      Sur  2024-03-03
6  Marcadores  Libreria    1800                10   Centro  2024-03-04
7     Carpeta  Libreria     950                18    Norte  2024-03-04
8        Goma  Libreria     300                30      Sur  2024-03-05
9       Lapiz  Libreria     250                50   Centro  2024-03-05

In [12]:
# también se puede indicar cuántas filas queremos ver
df.tail(3)

  producto categoria  precio  cantidad_vendida sucursal       fecha
7  Carpeta  Libreria     950                18    Norte  2024-03-04
8     Goma  Libreria     300                30      Sur  2024-03-05
9    Lapiz  Libreria     250                50   Centro  2024-03-05

## Conocer las dimensiones con shape

In [13]:
# (filas, columnas)
df.shape

(10, 6)

## Revisar los nombres de las columnas

In [14]:
# nombres de las columnas
df.columns

Index(['producto', 'categoria', 'precio', 'cantidad_vendida', 'sucursal',
       'fecha'],
      dtype='str')

## Revisar el índice del Dataframe

* El índice sirve para identificar las filas
* En muchos casos, Pandas crea automáticamente un índice numérico que empieza en 0

In [15]:
df.index

RangeIndex(start=0, stop=10, step=1)

## Revisar los tipos de datos

* En Pandas, cada columna tiene un tipo de dato asociado
* Ese tipo de dato le indica a Pandas cómo debe interpretar los valores de esa columna

In [16]:
df.dtypes

producto              str
categoria             str
precio              int64
cantidad_vendida    int64
sucursal              str
fecha                 str
dtype: object

## Obtener información general con info()

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   producto          10 non-null     str
 1   categoria         10 non-null     str
 2   precio            10 non-null     int64
 3   cantidad_vendida  10 non-null     int64
 4   sucursal          10 non-null     str
 5   fecha             10 non-null     str
dtypes: int64(2), str(4)
memory usage: 612.0 bytes

## Obtener estadísticas iniciales con describe()

In [18]:
# resumen estadístico (medidas descriptivas básicas) de columnas numéricas
df.describe()

            precio  cantidad_vendida
count    10.000000          10.00000
mean   1830.000000          21.30000
std    2509.338115          14.79527
min     250.000000           5.00000
25%     387.500000          10.50000
50%    1075.000000          16.50000
75%    1662.500000          28.75000
max    8500.000000          50.00000

| Medida       | Significado                  |
|--------------|------------------------------|
| ```count```  | Cantidad de valores no nulos |
| ```mean```   | Promedio                     |
| ```std```    | Desvío estándar              |
| ```min```    | Valor mínimo                 |
| ```25%```    | Primer cuartil               |
| ```50%```    | Mediana                      |
| ```75%```    | Tercer cuartil               |
| ```max```    | Valor máximo                 |

## Describir columnas no numérica

* Cuando usamos df.describe(), Pandas resume automáticamente las columnas numéricas
* Pero un dataset también puede tener columnas no numéricas, como producto, categoria o sucursal.
* Si queremos obtener un resumen de todas las columnas, podemos usar ```include='all'```

In [19]:
df.describe(include='all')

        producto categoria       precio  cantidad_vendida sucursal       fecha
count         10        10    10.000000          10.00000       10          10
unique         9         2          NaN               NaN        3           5
top     Cuaderno  Libreria          NaN               NaN   Centro  2024-03-01
freq           2         8          NaN               NaN        4           2
mean         NaN       NaN  1830.000000          21.30000      NaN         NaN
std          NaN       NaN  2509.338115          14.79527      NaN         NaN
min          NaN       NaN   250.000000           5.00000      NaN         NaN
25%          NaN       NaN   387.500000          10.50000      NaN         NaN
50%          NaN       NaN  1075.000000          16.50000      NaN         NaN
75%          NaN       NaN  1662.500000          28.75000      NaN         NaN
max          NaN       NaN  8500.000000          50.00000      NaN         NaN

* Para las columnas no numéricas, Pandas muestra otras medidas:

| Medida       | Significado                               |
|--------------|-------------------------------------------|
| ```count```  | Cantidad de valores no nulos              |
| ```unique``` | Cantidad de valores distintos             |
| ```top```    | Valor que aparece con mayor frecuencia    |
| ```freq```   | Frecuencia del valor más repetido         |

* En columnas como producto, que pueden tener muchos valores distintos, a veces conviene usar otras herramientas, como ```value_counts()```, para ver con más detalle la frecuencia de cada valor.

In [20]:
# ¿Cuántas ventas se registraron en cada sucursal?
df['sucursal'].value_counts()

sucursal
Centro    4
Norte     3
Sur       3
Name: count, dtype: int64

## Construir una primera lectura del dataset

| Pregunta                                                | Herramienta posible  |
|---------------------------------------------------------|----------------------|
| ¿Cómo son las primeras filas?	                          | ```head()```         |
| ¿Cómo son las últimas filas?                            | ```tail()```         |
| ¿Cuántas filas y columnas tiene?                        | ```shape```          |
| ¿Cómo se llaman las columnas?	                          | ```columns```        |
| ¿Cómo está identificado cada registro?                  | ```index```          |
| ¿Qué tipo de dato tiene cada columna?	                  | ```dtypes```         |
| ¿Hay valores faltantes visibles en el resumen?          | ```info()```         |
| ¿Qué resumen estadístico tienen las columnas numéricas? | ```describe()```     |
| ¿Cuántas veces aparece cada categoría?                  | ```value_counts()``` |

* Apartir de lo que vimos podemos decir:

> El dataset tiene 10 filas y 6 columnas.
>
> Cada fila representa una venta.
>
> Las columnas incluyen producto, categoria, precio, cantidad vendida, sucursal y fecha.
>
> Las columnas precio y cantidad_vendida son numéricas.
>
> La columna fecha parece una fecha, pero Pandas la interpreta todavía como texto.
>
> No se observan valores faltantes en este dataset.

* Este tipo de lectura inicial es muy importante. Antes de limpiar, transformar, agrupar o visualizar datos necesitamos saber qué tenemos delante

* Una buena práctica es no empezar directamente por los cálculos, sino dedicar unos minutos a revisar la estructura del dataset