# Selección, filtros y ordenamientos

## Selección de columnas en un dataframe

 * **Dataset de trabajo**: dataset pequeño de ventas de una librería

In [1]:
import pandas as pd

datos = {
    "producto": [
        "Cuaderno", "Lapicera", "Mochila", "Regla", "Cartuchera",
        "Cuaderno", "Marcadores", "Carpeta", "Goma", "Lapiz"
    ],
    "categoria": [
        "Libreria", "Libreria", "Accesorios", "Libreria", "Accesorios",
        "Libreria", "Libreria", "Libreria", "Libreria", "Libreria"
    ],
    "precio": [
        1200, 350, 8500, 500, 3200,
        1250, 1800, 950, 300, 250
    ],
    "cantidad_vendida": [
        15, 40, 5, 25, 8,
        12, 10, 18, 30, 50
    ],
    "sucursal": [
        "Centro", "Centro", "Norte", "Sur", "Norte",
        "Sur", "Centro", "Norte", "Sur", "Centro"
    ],
    "fecha": [
        "2024-03-01", "2024-03-01", "2024-03-02", "2024-03-02", "2024-03-03",
        "2024-03-03", "2024-03-04", "2024-03-04", "2024-03-05", "2024-03-05"
    ]
}

df = pd.DataFrame(datos)

df

     producto   categoria  precio  cantidad_vendida sucursal       fecha
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
1    Lapicera    Libreria     350                40   Centro  2024-03-01
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
3       Regla    Libreria     500                25      Sur  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
5    Cuaderno    Libreria    1250                12      Sur  2024-03-03
6  Marcadores    Libreria    1800                10   Centro  2024-03-04
7     Carpeta    Libreria     950                18    Norte  2024-03-04
8        Goma    Libreria     300                30      Sur  2024-03-05
9       Lapiz    Libreria     250                50   Centro  2024-03-05

* Un DataFrame puede tener muchas columnas
* Algunas pueden ser necesarias para una pregunta determinada y otras no
* Por ejemplo, si queremos comparar productos y precios, podemos seleccionar dos columnas: producto y precio

In [6]:
# Selección de la columna precio
# Panda devuelve una Series (estructura de una sola dimensión)
serie_precio = df['precio']
serie_precio

0    1200
1     350
2    8500
3     500
4    3200
5    1250
6    1800
7     950
8     300
9     250
Name: precio, dtype: int64

In [7]:
# Selección de la columna precio
# Panda devuelve un DataFrame con una sola columna
df_precio = df[['precio']]
df_precio

   precio
0    1200
1     350
2    8500
3     500
4    3200
5    1250
6    1800
7     950
8     300
9     250

In [8]:
# Selección de las columnas producto y precio
# Panda devuelve un DataFrame formado por las columnas seleccionadas
df_prod_precio = df[['producto', 'precio']]
df_prod_precio

     producto  precio
0    Cuaderno    1200
1    Lapicera     350
2     Mochila    8500
3       Regla     500
4  Cartuchera    3200
5    Cuaderno    1250
6  Marcadores    1800
7     Carpeta     950
8        Goma     300
9       Lapiz     250

In [10]:
# Aplicar una operación sobre una columna (min(), max(), mean(), sum(), ...)
df['precio'].mean()

np.float64(1830.0)

* Selección de columnas según la pregunta que queremos responder, permite enfocar el análisis en las variables que se necesitan
    1. Formular una pregunta de análisis
    2. Identificar que columnas se necesitan
    3. Aplicar las operaciones correspondientes (en Pandas)
    4. Interpretar resultados

## Selección de filas en un dataframe

* Las columnas representan variables
* Las filas representan observaciones, registros o casos
* Seleccionar filas significa elegir qué registros del dataset queremos observar

In [11]:
# Seleccionar una fila con iloc mediante posiciones numéricas
# Pandas devuelve una Series
df.iloc[0]

producto              Cuaderno
categoria             Libreria
precio                    1200
cantidad_vendida            15
sucursal                Centro
fecha               2024-03-01
Name: 0, dtype: object

In [13]:
# Seleccionar una fila con iloc mediante posiciones numéricas
# Pandas devuelve un DataFrame
df.iloc[[0]]

   producto categoria  precio  cantidad_vendida sucursal       fecha
0  Cuaderno  Libreria    1200                15   Centro  2024-03-01

In [12]:
# Seleccionar varias filas consecutivas
# Pandas devuelve un DataFrame
df.iloc[0:3]

   producto   categoria  precio  cantidad_vendida sucursal       fecha
0  Cuaderno    Libreria    1200                15   Centro  2024-03-01
1  Lapicera    Libreria     350                40   Centro  2024-03-01
2   Mochila  Accesorios    8500                 5    Norte  2024-03-02

In [14]:
# Seleccionar varias filas NO consecutivas
df.iloc[[0, 3, 9]]

   producto categoria  precio  cantidad_vendida sucursal       fecha
0  Cuaderno  Libreria    1200                15   Centro  2024-03-01
3     Regla  Libreria     500                25      Sur  2024-03-02
9     Lapiz  Libreria     250                50   Centro  2024-03-05

In [15]:
# Seleccionar filas y columnas con iloc
# df.iloc[fila, columna]
df.iloc[0, 0]

'Cuaderno'

In [17]:
df.iloc[[0, 1], [1, 2, 3]]

  categoria  precio  cantidad_vendida
0  Libreria    1200                15
1  Libreria     350                40

Con iloc, usamos posiciones numéricas. Para evitar confusiones, puede ser útil revisar primero el tamaño del DataFrame con shape y el orden de las columnas con list(df.columns)

## Selección con etiquetas usando loc

* ```iloc``` selecciona por posición
* ```loc``` selecciona por etiqueta
* Podemos indicar nombres de columnas y etiquetas del índice

In [18]:
# Selecciona la fila que está en la primera posición
df.iloc[0]

producto              Cuaderno
categoria             Libreria
precio                    1200
cantidad_vendida            15
sucursal                Centro
fecha               2024-03-01
Name: 0, dtype: object

In [19]:
# Selecciona la fila cuya etiqueta de índice es 0
df.loc[0]

producto              Cuaderno
categoria             Libreria
precio                    1200
cantidad_vendida            15
sucursal                Centro
fecha               2024-03-01
Name: 0, dtype: object

En este dataset, ambas instrucciones devuelven la misma fila porque el índice coincide con las posiciones. Pero esto no siempre será así. Si el índice estuviera formado por códigos, fechas o nombres, loc usaría esas etiquetas, no la posición física de la fila.

In [20]:
# Seleccionar varias filas con loc
df.loc[[0, 3, 5]]

   producto categoria  precio  cantidad_vendida sucursal       fecha
0  Cuaderno  Libreria    1200                15   Centro  2024-03-01
3     Regla  Libreria     500                25      Sur  2024-03-02
5  Cuaderno  Libreria    1250                12      Sur  2024-03-03

In [21]:
# Seleccionar una columna con loc
# df.loc[filas, columnas]
df.loc[:, 'precio']

0    1200
1     350
2    8500
3     500
4    3200
5    1250
6    1800
7     950
8     300
9     250
Name: precio, dtype: int64

In [22]:
# Seleccionar varias columnas con loc
df.loc[:, ['producto', 'precio']]

     producto  precio
0    Cuaderno    1200
1    Lapicera     350
2     Mochila    8500
3       Regla     500
4  Cartuchera    3200
5    Cuaderno    1250
6  Marcadores    1800
7     Carpeta     950
8        Goma     300
9       Lapiz     250

In [23]:
df.loc[0:3, ['producto', 'precio']]

   producto  precio
0  Cuaderno    1200
1  Lapicera     350
2   Mochila    8500
3     Regla     500

## Filtros con condiciones

* Filtrar significa quedarse solamente con los registros que cumplen cierto criterio. Por ejemplo, podríamos querer ver solo las ventas realizadas en la sucursal "Centro", solo los productos de la categoría "Libreria", solo las ventas con precio mayor a 1000, o solo los registros cuya cantidad vendida supere cierto valor

* Esta forma de selección es fundamental porque permite responder preguntas más específicas sobre los datos. Ya no elegimos filas por su posición ni por su etiqueta, sino por lo que esas filas contienen

In [25]:
# Construir una condición
# Devuelve una máscara booleana: serie que indica qué filas cumplen la condición
df['precio'] > 1000

0     True
1    False
2     True
3    False
4     True
5     True
6     True
7    False
8    False
9    False
Name: precio, dtype: bool

In [26]:
# Aplicar la máscara booleana para filtrar el DataFrame
df[df['precio'] > 1000]

     producto   categoria  precio  cantidad_vendida sucursal       fecha
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
5    Cuaderno    Libreria    1250                12      Sur  2024-03-03
6  Marcadores    Libreria    1800                10   Centro  2024-03-04

In [27]:
# Filtros con valores categóricos
df[df['sucursal'] == 'Centro']

     producto categoria  precio  cantidad_vendida sucursal       fecha
0    Cuaderno  Libreria    1200                15   Centro  2024-03-01
1    Lapicera  Libreria     350                40   Centro  2024-03-01
6  Marcadores  Libreria    1800                10   Centro  2024-03-04
9       Lapiz  Libreria     250                50   Centro  2024-03-05

In [28]:
# Filtrar valores incluidos en una lista
df[df['sucursal'].isin(['Centro', 'Norte'])]

     producto   categoria  precio  cantidad_vendida sucursal       fecha
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
1    Lapicera    Libreria     350                40   Centro  2024-03-01
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
6  Marcadores    Libreria    1800                10   Centro  2024-03-04
7     Carpeta    Libreria     950                18    Norte  2024-03-04
9       Lapiz    Libreria     250                50   Centro  2024-03-05

In [31]:
# Filtrar textos que contienen una palabra
df[df['producto'].str.contains('Cuad')]

   producto categoria  precio  cantidad_vendida sucursal       fecha
0  Cuaderno  Libreria    1200                15   Centro  2024-03-01
5  Cuaderno  Libreria    1250                12      Sur  2024-03-03

In [36]:
# Combinar filtros
# df[(condición_1) & (condición_2)]
# la categoría es Libreria
# el precio es mayor que 500
df[(df['categoria'] == 'Libreria') & (df['precio'] > 500)]

     producto categoria  precio  cantidad_vendida sucursal       fecha
0    Cuaderno  Libreria    1200                15   Centro  2024-03-01
5    Cuaderno  Libreria    1250                12      Sur  2024-03-03
6  Marcadores  Libreria    1800                10   Centro  2024-03-04
7     Carpeta  Libreria     950                18    Norte  2024-03-04

| Operador | Significado                           | Ejemplo                            |
|----------|---------------------------------------|------------------------------------|
| **&**    | deben cumplirse todas las condiciones | df[(condición_1) & (condición_2)]  |
| **\|**   | debe cumplirse al menos una condición | df[(condición_1) \| (condición_2)] |
| **~**    | niega una condición                   | df[~(condición_1)]                 |

## Ordenar datos en un dataframe

* Ordenar un ```DataFrame``` significa reorganizar sus filas según los valores de una o más columnas
* Esto permite leer mejor la información, encontrar rápidamente valores altos o bajos, comparar registros y construir primeros rankings

In [37]:
# Ordena un dataframe según los valores de una columna
# Por default ordena de menor a mayor
df.sort_values('precio')

     producto   categoria  precio  cantidad_vendida sucursal       fecha
9       Lapiz    Libreria     250                50   Centro  2024-03-05
8        Goma    Libreria     300                30      Sur  2024-03-05
1    Lapicera    Libreria     350                40   Centro  2024-03-01
3       Regla    Libreria     500                25      Sur  2024-03-02
7     Carpeta    Libreria     950                18    Norte  2024-03-04
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
5    Cuaderno    Libreria    1250                12      Sur  2024-03-03
6  Marcadores    Libreria    1800                10   Centro  2024-03-04
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02

In [40]:
df.sort_values('precio', ascending=False)

     producto   categoria  precio  cantidad_vendida sucursal       fecha
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
6  Marcadores    Libreria    1800                10   Centro  2024-03-04
5    Cuaderno    Libreria    1250                12      Sur  2024-03-03
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
7     Carpeta    Libreria     950                18    Norte  2024-03-04
3       Regla    Libreria     500                25      Sur  2024-03-02
1    Lapicera    Libreria     350                40   Centro  2024-03-01
8        Goma    Libreria     300                30      Sur  2024-03-05
9       Lapiz    Libreria     250                50   Centro  2024-03-05

In [39]:
# Ordena columnas de texto (en forma alfabetica)
df.sort_values('producto')

     producto   categoria  precio  cantidad_vendida sucursal       fecha
7     Carpeta    Libreria     950                18    Norte  2024-03-04
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
5    Cuaderno    Libreria    1250                12      Sur  2024-03-03
8        Goma    Libreria     300                30      Sur  2024-03-05
1    Lapicera    Libreria     350                40   Centro  2024-03-01
9       Lapiz    Libreria     250                50   Centro  2024-03-05
6  Marcadores    Libreria    1800                10   Centro  2024-03-04
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
3       Regla    Libreria     500                25      Sur  2024-03-02

In [41]:
df.sort_values('producto', ascending=False)

     producto   categoria  precio  cantidad_vendida sucursal       fecha
3       Regla    Libreria     500                25      Sur  2024-03-02
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
6  Marcadores    Libreria    1800                10   Centro  2024-03-04
9       Lapiz    Libreria     250                50   Centro  2024-03-05
1    Lapicera    Libreria     350                40   Centro  2024-03-01
8        Goma    Libreria     300                30      Sur  2024-03-05
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
5    Cuaderno    Libreria    1250                12      Sur  2024-03-03
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
7     Carpeta    Libreria     950                18    Norte  2024-03-04

In [42]:
# Ordena varias columnas
df.sort_values(['categoria', 'precio'])

     producto   categoria  precio  cantidad_vendida sucursal       fecha
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
9       Lapiz    Libreria     250                50   Centro  2024-03-05
8        Goma    Libreria     300                30      Sur  2024-03-05
1    Lapicera    Libreria     350                40   Centro  2024-03-01
3       Regla    Libreria     500                25      Sur  2024-03-02
7     Carpeta    Libreria     950                18    Norte  2024-03-04
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
5    Cuaderno    Libreria    1250                12      Sur  2024-03-03
6  Marcadores    Libreria    1800                10   Centro  2024-03-04

In [43]:
# Ordena varias columnas por distintos criterios
df.sort_values(['categoria', 'precio'], ascending=[True, False])

     producto   categoria  precio  cantidad_vendida sucursal       fecha
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
6  Marcadores    Libreria    1800                10   Centro  2024-03-04
5    Cuaderno    Libreria    1250                12      Sur  2024-03-03
0    Cuaderno    Libreria    1200                15   Centro  2024-03-01
7     Carpeta    Libreria     950                18    Norte  2024-03-04
3       Regla    Libreria     500                25      Sur  2024-03-02
1    Lapicera    Libreria     350                40   Centro  2024-03-01
8        Goma    Libreria     300                30      Sur  2024-03-05
9       Lapiz    Libreria     250                50   Centro  2024-03-05

In [46]:
# Combinar filtros, ordenamiento y selección de columnas
df[df['categoria'] == 'Libreria'].sort_values('precio', ascending=False)[['producto', 'categoria', 'precio']]

     producto categoria  precio
6  Marcadores  Libreria    1800
5    Cuaderno  Libreria    1250
0    Cuaderno  Libreria    1200
7     Carpeta  Libreria     950
3       Regla  Libreria     500
1    Lapicera  Libreria     350
8        Goma  Libreria     300
9       Lapiz  Libreria     250

## Valores extremos y primeros rankings

* Valores más altos o más bajos de una variable

In [47]:
# Precios altos
df.sort_values('precio', ascending=False).head(3)

     producto   categoria  precio  cantidad_vendida sucursal       fecha
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
6  Marcadores    Libreria    1800                10   Centro  2024-03-04

In [48]:
# Precios bajos
df.sort_values('precio', ascending=False).tail(3)

   producto categoria  precio  cantidad_vendida sucursal       fecha
1  Lapicera  Libreria     350                40   Centro  2024-03-01
8      Goma  Libreria     300                30      Sur  2024-03-05
9     Lapiz  Libreria     250                50   Centro  2024-03-05

In [49]:
# Obtener los mayores valores con nlargest()
df.nlargest(3, 'precio')

     producto   categoria  precio  cantidad_vendida sucursal       fecha
2     Mochila  Accesorios    8500                 5    Norte  2024-03-02
4  Cartuchera  Accesorios    3200                 8    Norte  2024-03-03
6  Marcadores    Libreria    1800                10   Centro  2024-03-04

In [50]:
# Obtener los menores valores con nsmallest()
df.nsmallest(3, 'precio')

   producto categoria  precio  cantidad_vendida sucursal       fecha
9     Lapiz  Libreria     250                50   Centro  2024-03-05
8      Goma  Libreria     300                30      Sur  2024-03-05
1  Lapicera  Libreria     350                40   Centro  2024-03-01